### ISSUE TITLE
MySQL expressions

### ISSUE THREAD

**Issue by coolbox** [asmuth/fviz#216]
Am i right in understanding that not all standard MySql functions are available? 

For example i'm trying to run the following simple query on a database table to display the number of signups per month:

```
SELECT 
DATE_FORMAT(created, "%m/%y") AS x,
COUNT(uid) AS y
FROM users
GROUP BY YEAR(created), MONTH(created)
ORDER BY YEAR(created), MONTH(created)
```

…but i'm getting the following error: `symbol not found: DATE_FORMAT`. I continue to see this for the other functions i've used too: `symbol not found: YEAR` and `symbol not found: MONTH`.

I've found the [documentation for the built in DateTime functions](http://fnordmetric.io/documentation/chartsql/built_in_functions/), but they seem quite limited.

Are there any work arounds for achieving what i am trying to achieve?

**Comment by henrik-muehe** [comment]
From my rough understanding of the code, it actually creates its own query plan and does its own SQL parsing. This means that the amount of SQL which is supported is restricted to the set of implemented operations in fnordmetric. I agree that this is a severe limitation but it is a very fundamental design choice in the backend.

To work around this, what you should be able to do easily is **create a view** in your database and query that. Now fnordmetric should cooperate nicely as it does not see the complex expressions in the query anymore.

**Comment by paulasmuth** [comment]
Yes, it is correct that FnordMetric will currently build it's own query plan and only execute a simple select statement on the backend SQL database. 

The reason why it was built this way in the first place, is becase the code started out as a SQL frontend for non-SQL data sources. One reason why it might make sense to keep it this way is that you otherwise wouldn't be able to implement a feature like joining a table from a CSV file with table from a MySQL backend in the future. 

However one thing that should be possible and is planned for a later version is to branch out the case where we only have a single backend involved in the query that supports full SQL. In that case it should be relatively straightforward to "push down" the full SELECT statement into the backend database.

Hope that makes sense.

**Comment by henrik-muehe** [comment]
So Paul, in general that should also be done for the multiple backend case. You essentially try to reorder and pushdown anything that can be executed in one backend at once so that you'd get the maximum reduction in data size before it's transferred into fnordmetric even if it is then joined to something from another backend.

In general, pushing most elements of the query into the sql database is indispensable as the backend (sql db) might store more data than you can handle in the in-memory frontend. I'll think a bit about that part as well...

**Comment by paulasmuth** [comment]
I agree that we should push as much of the execution tree down into the backends if they support SQL for performance reasons. However that requires us to build a query plan for the query first (so that we can subsequently re-serialize parts of it and send it to the backend SQL servers) and the problem in this case is that we can't even do that.

So what I was thinking about was more of a "hack" in which we only implement the more complex/MySQL specific stuff in the parser so we can build the AST but don't have to implement it in the actual query engine. It should still be possible (by looking at the AST) to tell if the query executes against more than one backend and if not, just remove the whole select statement from the AST, or even better, replace it with a SERIALIZED_SELECT_STATEMENT node so we can just send it off to the backend server as is.

BTW the FnordMetric SQL execution could should not require to keep the full working set in memory  -- that is if the SQL query itself doesn't require it, like e.g. a group/order by (FnordMetric currently can't write temp tables to disk)
